## Contoh 1: Membangun Logika Fuzzy Metode Mamdani

In [2]:
import numpy as np

# Define the input values (homework and exam scores)
homework_score = 80  # For example, homework score of 45
exam_score = 75     # For example, exam score of 75

In [4]:
# Define the fuzzy sets for homework and exam scores
homework_low = np.array([0, 30, 60])
homework_medium = np.array([30, 70, 100])
homework_high = np.array([70, 100, 100])

exam_low = np.array([0, 30, 60])
exam_medium = np.array([30, 70, 100])
exam_high = np.array([70, 100, 100])

# Calculate the membership values for each input in the fuzzy sets
homework_low_membership = np.interp(homework_score, homework_low, [0, 1, 0])
homework_medium_membership = np.interp(homework_score, homework_medium, [0, 1, 0])
homework_high_membership = np.interp(homework_score, homework_high, [0, 1, 0])

exam_low_membership = np.interp(exam_score, exam_low, [0, 1, 0])
exam_medium_membership = np.interp(exam_score, exam_medium, [0, 1, 0])
exam_high_membership = np.interp(exam_score, exam_high, [0, 1, 0])

# Define the fuzzy rules
rules = [
    (min(homework_low_membership, exam_low_membership), "grade_low"),
    (min(homework_medium_membership, exam_low_membership), "grade_medium"),
    (min(homework_high_membership, exam_low_membership), "grade_medium"),
    (min(homework_low_membership, exam_medium_membership), "grade_medium"),
    (min(homework_medium_membership, exam_medium_membership), "grade_medium"),
    (min(homework_high_membership, exam_medium_membership), "grade_high"),
    (min(homework_low_membership, exam_high_membership), "grade_high"),
    (min(homework_medium_membership, exam_high_membership), "grade_high"),
    (min(homework_high_membership, exam_high_membership), "grade_high"),
]

# Aggregate the rule outputs
grades = {
    "grade_low": 0,
    "grade_medium": 0,
    "grade_high": 0,
}

for rule in rules:
    membership, grade = rule
    grades[grade] = max(grades[grade], membership)

# Calculate the centroid defuzzified grade
defuzzified_grade = (grades["grade_low"] * 30 + grades["grade_medium"] * 70 + grades["grade_high"] * 100) / (grades["grade_low"] + grades["grade_medium"] + grades["grade_high"])

if defuzzified_grade <= 40:
    output_grade = "Low"
elif defuzzified_grade <= 70:
    output_grade = "Medium"
else:
    output_grade = "High"

# Output the recommended grade
print("Recommended Grade:", output_grade)

Recommended Grade: High

## Tugas Praktikum

In [16]:
import numpy as np
import pandas as pd

# Data
data = {
    'Name': ['Jasmine', 'Rafik', 'Mutia', 'Patrik', 'Fajar'],
    'Tugas 1': [70, 90, 50, 10, 65],
    'Tugas 2': [80, 80, 55, 0, 35],
    'Tugas 3': [75, 80, 60, 90, 100],
    'UTS': [80, 77, 10, 60, 70],
    'UAS': [40, 90, 30, 70, 72]
}

df = pd.DataFrame(data)
df

      Name  Tugas 1  Tugas 2  Tugas 3  UTS  UAS
0  Jasmine       70       80       75   80   40
1    Rafik       90       80       80   77   90
2    Mutia       50       55       60   10   30
3   Patrik       10        0       90   60   70
4    Fajar       65       35      100   70   72

In [17]:
# Definisi fuzzy set untuk skor tugas, UTS, dan UAS
tugas_low = np.array([0, 30, 60])
tugas_medium = np.array([30, 70, 100])
tugas_high = np.array([70, 100, 100])

uts_low = np.array([0, 30, 60])
uts_medium = np.array([30, 70, 100])
uts_high = np.array([70, 100, 100])

uas_low = np.array([0, 30, 60])
uas_medium = np.array([30, 70, 100])
uas_high = np.array([70, 100, 100])

for index, row in df.iterrows():
    tugas_score = (row[['Tugas 1', 'Tugas 2', 'Tugas 3']]).mean()
    tugas_low_membership = np.interp(tugas_score, tugas_low, [1, 2, 1])
    tugas_medium_membership = np.interp(tugas_score, tugas_medium, [1, 2, 1])
    tugas_high_membership = np.interp(tugas_score, tugas_high, [1, 2, 1])
    
    uts_low_membership = np.interp(row['UTS'], uts_low, [1, 2, 1])
    uts_medium_membership = np.interp(row['UTS'], uts_medium, [1, 2, 1])
    uts_high_membership = np.interp(row['UTS'], uts_high, [1, 2, 1])
    
    uas_low_membership = np.interp(row['UAS'], uas_low, [1, 2, 1])
    uas_medium_membership = np.interp(row['UAS'], uas_medium, [1, 2, 1])
    uas_high_membership = np.interp(row['UAS'], uas_high, [1, 2, 1])
    
    rules = [
        (min(tugas_low_membership, uts_low_membership, uas_low_membership), "C"),
        (min(tugas_medium_membership, uts_low_membership, uas_low_membership), "B"),
        (min(tugas_high_membership, uts_low_membership, uas_low_membership), "B"),
        (min(tugas_low_membership, uts_medium_membership, uas_medium_membership), "B"),
        (min(tugas_medium_membership, uts_medium_membership, uas_medium_membership), "B"),
        (min(tugas_high_membership, uts_medium_membership, uas_medium_membership), "A"),
        (min(tugas_low_membership, uts_high_membership, uas_high_membership), "A"),
        (min(tugas_medium_membership, uts_high_membership, uas_high_membership), "A"),
        (min(tugas_high_membership, uts_high_membership, uas_high_membership), "A"),
    ]
    
    grades = {
        "C": 0,
        "B": 0,
        "A": 0,
    }

    for rule in rules:
        membership, grade = rule
        grades[grade] = max(grades[grade], membership)

    defuzzified_grade = (grades["C"] * 1 + grades["B"] * 2 + grades["A"] * 3) / (
        grades["C"] + grades["B"] + grades["A"]
    )

    if defuzzified_grade < 1.5:
        nilai_akhir = "C"
    elif defuzzified_grade >= 1.5 and defuzzified_grade < 2.5:
        nilai_akhir = "B"
    else:
        nilai_akhir = "A"
    
    df.at[index, 'Nilai Akhir'] = nilai_akhir

print(df)

      Name  Tugas 1  Tugas 2  Tugas 3  UTS  UAS Nilai Akhir
0  Jasmine       70       80       75   80   40           B
1    Rafik       90       80       80   77   90           B
2    Mutia       50       55       60   10   30           B
3   Patrik       10        0       90   60   70           B
4    Fajar       65       35      100   70   72           B